services:
  postgres:
    image: postgres:15.10
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goa

volumes:
  postgres_data:
    name: "postgres-data"

networks:
  goa:
    external: true

# Construir todas las BD
#> docker compose -f docker-compose-db.yml -p databases up -d

# CONSOLA & COMANDOS MySQL
#> docker exec -it mysql-server mysql -u root -p
#  show databases;
#  create database poo;
#  drop database poo;
#  use poo;
#  show tables;
#  describe mytable;
#  select * from mytable;
#  drop table mytable;
#  exit

# CONSOLA & COMANDOS Postgres
#> docker exec -it postgres-server  psql -U postgres
#  \?   Help
#  \l   Database list
#  \connect <db> <usr>
#  \dt   Table list
#  \d <table> ;  describe
#  \q   exit
#  create database <db>;
#  drop database <db>;
#  select * from <table>;
#  delete from <table>;

# CONSOLA & COMANDOS mongo
#> docker exec -it mongo-server mongosh "mongodb://mongo:mongo@localhost:27017/devops?authSource=admin"
#  help
#  db.version()
#  db.stats()
#  show databases
#  use <myBD>
#  show collections
#  db.dropDatabase()
#  db.coll1.drop()
#  db.coll1.find()
#  db.coll1.find().pretty()
#  db.coll1.count()
