services:
  goa-user:
    build: .
    image: goa-user:1.0.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/goauser
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    networks:
      - goa

networks:
  goa:
    external: true

#> docker compose -f docker-compose-dev.yml up --build -d

#> ports: -"0:8081" or -"8081" or remove
#> docker-compose -f docker-compose-dev.yml -p tpv-articles up --scale tpv-article=2 -d
