services:
  goa-user:
    build: .
    image: goa-user:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongo:27017/goauserdb?authSource=admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/goauserdb
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    networks:
      - goa
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  goa:
    external: true

#> docker compose up --build -d

# Para crear una basses de datos:
#> docker exec -e PGPASSWORD='password' -it postgres-server psql -U userPostgres -d postgres -c "CREATE DATABASE goauserdb;"
# Para ver los logs de arranque
#> docker logs -f goa-user