spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      clients:
        issuer-uri: ${ISSUER_URI}
        spa-client-id: spaClientId
        spa-login-redirect-uri: ${SPA_LOGIN_REDIRECT_URI}
        spa-logout-redirect-uri: ${SPA_LOGOUT_REDIRECT_URI}
        api-client-id: ${API_CLIENT_ID}
        api-client-secret: ${API_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://goa-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
