spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-server:5432/goauser
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      clients:
        issuer: https://gestion.ocanabogados.es/api/goa-user
        spa-client-id: spaClientId
        spa-login-redirect-uri: https://gestion.ocanabogados.es/callback
        spa-logout-redirect-uri: https://gestion.ocanabogados.es
        api-client-id: ${API_CLIENT_ID}
        api-client-secret: ${API_CLIENT_SECRET}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
