spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      authorizationserver:
        issuer-uri: ${BASE_URL}/api/goa-user

app:
  db:
    mobile: ${DB_MOBILE}
    password: ${DB_PASSWORD}
  hosting: AWS
  oauth2:
    token-uri: ${BASE_URL}/api/goa-user/oauth2/token
    spa-client-id: spaClientId
    spa-login-redirect-uri: ${BASE_URL}/callback
    spa-logout-redirect-uri: ${BASE_URL}
    api-client-id: ${API_CLIENT_ID}
    api-client-secret: ${API_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://goa-eureka:8761/eureka/

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
