server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/goauser
    username: postgres
    password: postgres
  security:
    oauth2:
      clients:
        issuer: https://gestion.ocanabogados.es/api/goa-user
        open-api-client-id: ${OPEN_API_CLIENT_ID}
        open-api-client-secret: ${OPEN_API_CLIENT_SECRET}
        open-api-redirect-uris:
          - https://gestion.ocanabogados.es/oauth2-redirect.html
        spa-client-id: ${SPA_CLIENT_ID}
        spa-login-redirect-uri: https://gestion.ocanabogados.es/callback
        spa-logout-redirect-uri: https://gestion.ocanabogados.es
        api-client-id: ${API_CLIENT_ID}
        api-client-secret: ${API_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://goa-eureka:8761/eureka/