name: CI
on:
  push:
    branches: [ develop,release-* ]

jobs:
  ci:
    name: Test - Unit & Integration & SonarCloud Scan & Slack WebHook
    runs-on: ubuntu-22.04
    steps:
      - name: clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: maven

      - name: Extract version from pom.xml
        id: get-version
        run: echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      - name: Build & Unit & IT & FT & Sonar Analysis
        run: >
          mvn -B clean verify sonar:sonar 
          -Dsonar.projectKey=miw-upm-github_${{ env.ARTIFACT }}
          -Dsonar.organization=miw-upm-github 
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
